# שלב build
FROM node:20 as builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# שלב הפצה
FROM nginx:alpine

COPY --from=builder /app/dist/ /usr/share/nginx/html/


# הגדרות nginx אם יש לך קובץ משלך:
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
