version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: cv_backend_dev
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app:cached   # 👈 הוסיפי שורה זו
    networks:
      - cv_net


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: cv_frontend_dev
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app:cached
      - node_modules_frontend:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - cv_net

networks:
  cv_net:

volumes:
  node_modules_frontend:
