name: Deploy to EC2 on Push

on:
  push:
    branches:
      - main  # עדכני אם את עובדת על ענף אחר

jobs:
  deploy:
    name: Build & Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd ~/cv-dashboard   # ודאי שזה הנתיב בשרת שלך
            git pull origin main
            docker-compose -f docker-compose.production.yml build
            docker-compose -f docker-compose.production.yml up -d
            docker image prune -f
          EOF
