services:
  backend:
    build:
      context: ./backend
    container_name: cv_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: cv_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
