version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: cv_backend_prod
    ports:
      - "8200:8000"
    env_file:
      - ./backend/.env.production
    networks:
      - cv_net

  frontend:
    build:
      context: ./frontend
    container_name: cv_frontend_prod
    ports:
      - "5175:80"
    environment:
      - NODE_ENV=production
    env_file:
      - ./frontend/.env.production
    depends_on:
      - backend
    networks:
      - cv_net

networks:
  cv_net:
