version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: cv_backend_staging
    ports:
      - "8100:8000"
    env_file:
      - ./backend/.env
    networks:
      - cv_net

  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: development
    container_name: cv_frontend_staging
    ports:
      - "5174:5173"
    environment:
      - NODE_ENV=development

    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - cv_net

networks:
  cv_net:


