version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: cv_backend_prod
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - cv_net

  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=production
    container_name: cv_frontend_prod
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - cv_net

networks:
  cv_net:
